# 스프링 설정
spring:
  application:
    name: jwt-test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa
    username: root
    password: digh1212
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

# 서버 설정
server:
  port: 10000

# 사용자 정의 설정 (JWT 등)
jwt:
  secretKey: test1234